# Tokyo Night Light

# Default colors
foreground #3760bf
background #d5d6db

# Selection
selection_foreground #3760bf
selection_background #99a7df

# Cursor
cursor #3760bf
cursor_text_color #d5d6db

# Black
color0  #e9e9ed
color8  #a1a6c5

# Red
color1  #f52a65
color9  #f52a65

# Green
color2  #587539
color10 #587539

# Yellow
color3  #8c6c3e
color11 #8c6c3e

# Blue
color4  #2e7de9
color12 #2e7de9

# Magenta
color5  #9854f1
color13 #9854f1

# Cyan
color6  #007197
color14 #007197

# White
color7  #6172b0
color15 #3760bf

# Extended colors
mark1_foreground #d5d6db
mark1_background #2e7de9
mark2_foreground #d5d6db
mark2_background #9854f1
mark3_foreground #d5d6db
mark3_background #007197

# Tab bar
active_tab_foreground   #d5d6db
active_tab_background   #2e7de9
inactive_tab_foreground #3760bf
inactive_tab_background #c4c8da
tab_bar_background      #b4b5b9
